apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "resource_name" . }}
  labels:
    {{- include "labels" . | indent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.ingress.ui.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "resource_name" . }}
          servicePort: 80
        path: /
